### PR TITLE
draft mode for graphicx

### PR DESCRIPTION
**Pull request by cifera**
Hello,
draft mode does not remove images for me on TeX 3.14159265 (TeX Live 2015/Debian) due to
https://texwelt.de/wissen/fragen/2673/warum-werden-trotz-draft-option-bilder-geladen
Help me make a better if clause, please :)
Also, why not use bookmarks, they are neat!

Thanks for this great template!

### CODE REVIEW

**Comment by novoid** [comment]
Well, opened bookmarks in the PDF reader is a matter of personal taste.

The second change with graphicx I don't understand. What is the difference between "adding or removing the draft option" in contrast to "setting the new boolean to true or false"?

**Comment by cifera** [comment]
Hello,

thanks for your reply!
\usepackage[pdftex,draft]{graphicx} works as expected \usepackage[pdftex]{graphicx} does not. 
From the link
>Die meisten Pakete verstehen immer noch nur die normalen Optionen. D.h., dass z.B. graphicx nur mit der Option draft etwas anfangen kann. draft=true hingegen kennt es nicht und ignoriert es.
 
Maybe newer versions do not have this problem.
I use the former when \mydraft is set to true. Never done a if in Tex before the only way it worked was by comparing \mydraft with a variable that was set to true, this  variable is I called  \mytrue. Stupid but works, help.

bookmarksopen is the one which opens the tree, a matter of taste, sure.  
bookmarks creates them in the first place so bookmarks=false: no bookmarks less fun. 
Cheers :)

**Comment by novoid** [comment]
Hm, sorry for the mixup - it's been a while since I had the pleasure of using LaTeX ;-)

I'll take a look at the graphicx issue.

Meanwhile thanks for the issue!

**Comment by novoid** [comment]
Weird. In http://texdoc.net/texmf-dist/doc/latex/koma-script/scrguide.pdf the `draft`-switch only toggles activation of boxes that give a hint for overfull lines. It does not mention anything about replacing included graphics with rectangles. Either this was my fault right from the beginning or the behavior did change in-between.

However, I added an `ifthenelse`-switch for the `graphicx` command so that `\mydraft` also toggles rectangles for images.

And I activated generating the PDF bookmarks ;-)

Thanks for pointing me to this issue!

HTH

**Pull request closed without merging**
